### =========================================
### AUTENTICACIÓN ADMINISTRADOR - ADMIN LOGIN
### =========================================

### 0. Login administrador y guardar token JWT automáticamente

POST http://localhost:8080/api/login
Content-Type: application/json

{
"username": "<ADMIN_EMAIL>",
"password": "<ADMIN_PASSWORD>"
}

> {%
client.global.set("adminToken", response.body.access_token);
%}

### =========================================
###         PRUEBAS DE PRODUCTOS
### =========================================

### 1. [ADMIN] Ver todos los productos
GET http://localhost:8080/products
Accept: application/json
Authorization: Bearer {{adminToken}}

### 2. [ADMIN] Crear un producto nuevo
POST http://localhost:8080/products
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Montadito de Jamón",
  "description": "Jamón ibérico con aceite",
  "price": 2.50,
  "category": "MONTADITO",
  "imageUrl": "https://ejemplo.com/jamon.png"
}

### 3. [ADMIN] Ver productos sin stock
GET http://localhost:8080/products/out-of-stock
Accept: application/json
Authorization: Bearer {{adminToken}}