### =========================================
### AUTENTICACIÓN ADMINISTRADOR - ADMIN LOGIN
### =========================================

### 0. Login administrador y guardar token JWT automáticamente

POST http://localhost:8080/api/login
Content-Type: application/json

{
"username": "admin@smartqr.com",
"password": "Admin123!"
}

> {%
client.global.set("adminToken", response.body.access_token);
%}

### =========================================
###     GENERACIÓN QR - ADMIN
### =========================================
### Generar y guardar QR para la Mesa 5

POST http://localhost:8080/qr/table/5
Accept: image/png
Authorization: Bearer {{adminToken}}

### =========================================
###         PRUEBAS DE PRODUCTOS
### =========================================

### 1. [ADMIN] Ver todos los productos
GET http://localhost:8080/products
Accept: application/json
Authorization: Bearer {{adminToken}}

### 2. [ADMIN] Crear un producto nuevo
POST http://localhost:8080/products
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Montadito de Jamón",
  "description": "Jamón ibérico con aceite",
  "price": 2.50,
  "category": "MONTADITO",
  "imageUrl": "https://ejemplo.com/jamon.png"
}

### 3. [ADMIN] Ver productos sin stock
GET http://localhost:8080/products/out-of-stock
Accept: application/json
Authorization: Bearer {{adminToken}}

### =========================================
###         DASHBOARD DE METRICAS - ADMIN
### =========================================

### 4. [ADMIN] Consultar metricas generales del dashboard

GET http://localhost:8080/dashboard/metrics
Accept: application/json
Authorization: Bearer {{adminToken}}


### =========================================
###         GRAFICOS PNG - ADMIN
### =========================================

### 5. [ADMIN] Generar grafico de ingresos por metodo de pago
### El endpoint devuelve la imagen PNG y tambien la guarda localmente en:
### requests/charts/income-by-payment-method.png

GET http://localhost:8080/dashboard/charts/income-by-payment-method
Accept: image/png
Authorization: Bearer {{adminToken}}


### 6. [ADMIN] Generar grafico de productos vendidos
### El endpoint devuelve la imagen PNG y tambien la guarda localmente en:
### requests/charts/product-sales.png

GET http://localhost:8080/dashboard/charts/product-sales
Accept: image/png
Authorization: Bearer {{adminToken}}

